// This file is generated by Gemini.
'use server';

/**
 * @fileOverview Rewrites client testimonials to be more impactful and engaging.
 *
 * - enhanceTestimonial - A function that enhances the testimonial.
 * - EnhanceTestimonialInput - The input type for the enhanceTestimonial function.
 * - EnhanceTestimonialOutput - The return type for the enhanceTestimonial function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceTestimonialInputSchema = z.object({
  testimonial: z
    .string()
    .describe('The client testimonial to be enhanced.'),
});
export type EnhanceTestimonialInput = z.infer<typeof EnhanceTestimonialInputSchema>;

const EnhanceTestimonialOutputSchema = z.object({
  enhancedTestimonial: z
    .string()
    .describe('The enhanced client testimonial.'),
});
export type EnhanceTestimonialOutput = z.infer<typeof EnhanceTestimonialOutputSchema>;

export async function enhanceTestimonial(input: EnhanceTestimonialInput): Promise<EnhanceTestimonialOutput> {
  return enhanceTestimonialFlow(input);
}

const prompt = ai.definePrompt({
  name: 'enhanceTestimonialPrompt',
  input: {schema: EnhanceTestimonialInputSchema},
  output: {schema: EnhanceTestimonialOutputSchema},
  prompt: `You are an expert marketing copywriter specializing in rewriting client testimonials to be more impactful and engaging.

  Rewrite the following testimonial to be more impactful and engaging, capturing user interest and highlighting the key benefits of the service mentioned in the testimonial:

  Original Testimonial: {{{testimonial}}}

  Enhanced Testimonial:`,
});

const enhanceTestimonialFlow = ai.defineFlow(
  {
    name: 'enhanceTestimonialFlow',
    inputSchema: EnhanceTestimonialInputSchema,
    outputSchema: EnhanceTestimonialOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
